  --- Support for multiple Github servers
  create table ghservers
  (
  ghserverid int unique not null,
  serveruri varchar(255) not null
) organize by row;

  --- Repository data
  create table repos
  (
  rid int unique not null generated by default as identity (start with 1000, increment by 1),
  rname varchar(255) not null,
  ghserverid int not null,
  oid int not null,  --- this is the org or user
  schedule int not null
  ) organize by row;

  --- Github traffic for views and clones
  create table repotraffic
  (
  rid int,
  tdate date,
  viewcount int,
  vuniques int,
  clonecount int,
  cuniques int
  ) organize by row;

create index repotraffic_ix_tdate on repotraffic(tdate);

  --- The user which accesses Github, hence the token and ghuser name
  create table tenants
  (
  tid int unique not null generated by default as identity (start with 1000, increment by 1),
  fname varchar(100),
  lname varchar(100),
  email varchar(255),
  ghuser varchar(255) not null,
  ghtoken varchar(255) not null
) organize by row;


  --- Github user or org, needed for full repository name
  create table ghorgusers
  (
  oid int unique not null generated by default as identity (start with 1000, increment by 1),
  username varchar(255) not null,
  usertype char(1),
  email varchar(255),
  blog varchar(255)
  ) organize by row;

  --- connection between tenants and repos
  create table tenantrepos
  (
  tid int not null,
  rid int not null
  )  organize by row;

  --- info about last collection runs
  create table systemlog
  (
  tid int not null,
  completed timestamp,
  numrepos int,
  state varchar(255)
) organize by row;

  --- system administration
  create table adminusers
  (
  aid int unique not null generated by default as identity (start with 1000, increment by 1),
  auser varchar(255) not null,
  email varchar(255) not null
  ) organize by row;

  --- who has which roles, if admin or maintainer then only entry here
  create table adminroles
  (
  aid int not null,
  role int not null
  ) organize by row;

  --- if role regarding specific tenant or specific repository, then entry here, too
  create table admintenantreporoles
  (
  aid int not null,
  tid int not null,
  role int not null,
  rid int
  ) organize by row;

  --- What roles are available?
  create table adminrolevalues
  (
  role int unique not null,
  desc varchar(255) not null
  ) organize by row;

  --- initialize those FYI values
  insert into adminrolevalues values (1,'admin'),(2,'sysmaint'),(4,'tenant'),(8,'tenantstats'),(16,'repostats');

  --- view to list available repos per role and adminuser (identified by email)
  create view v_adminuserrepos as
  (
  select tr.rid, au.aid,au.email, atrr.role from  admintenantreporoles atrr, adminusers au, adminroles ar, tenantrepos tr
  where ar.aid=au.aid
  and atrr.aid=au.aid
  and tr.tid=atrr.tid
  and (bitand(atrr.role,8)>0 or bitand(atrr.role,4)>0)
  union all
  select tr.rid, au.aid,au.email, atrr.role from  admintenantreporoles atrr, adminusers au, adminroles ar, tenantrepos tr
  where ar.aid=au.aid
  and atrr.aid=au.aid
  and tr.tid=atrr.tid
  and tr.rid=atrr.rid
  and (bitand(atrr.role,16)>0)
  );

  --- view to show statistics for all repos and include full organisation name
  create view v_repostats as (
  select r.rid, username as orgname, rname as reponame, tdate, viewcount, vuniques, clonecount, cuniques from repotraffic rt, ghorgusers gu, repos r where r.oid=gu.oid and rt.rid=r.rid
  );

  --- view to include the organisation name into the available repos
  create view v_adminrepolist as
  (
  select r.rid, gu.username as orgname, r.rname as reponame, v.email from ghorgusers gu, repos r, v_adminuserrepos v where r.oid=gu.oid and v.rid=r.rid
  );
